# AUTOGENERATED FROM 'app/sample_data/inserts.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class InsertsResult(NoPydanticValidation):
    id: uuid.UUID


async def inserts(
    executor: edgedb.AsyncIOExecutor,
) -> InsertsResult | None:
    return await executor.query_single(
        """\
        # Create users first
        insert User {
            name := 'alice',
            facts := 'Interested in machine learning and data science. Works as a research scientist.',
        };

        insert User {
            name := 'bob',
            facts := 'Software engineer specializing in backend development. Enjoys reading about distributed systems.',
        };

        # Insert chat histories for Alice

        update User
        filter .name = 'alice'
        set {
            chats := {
                (insert ChatHistory {
                    summary := 'Discussion about large language models and their applications',
                    messages := {
                        (insert Message {
                            role := 'user',
                            body := 'What are the main differences between GPT-3 and GPT-4?',
                            timestamp := <datetime>'2024-01-07T10:00:00Z',
                            sources := {'arxiv:2303.08774', 'openai.com/research/gpt-4'}
                        }),
                        (insert Message {
                            role := 'assistant',
                            body := 'The key differences include improved reasoning capabilities, better context understanding, and enhanced safety features...',
                            timestamp := <datetime>'2024-01-07T10:00:05Z',
                            sources := {'openai.com/blog/gpt-4-details', 'arxiv:2303.08774'}
                        })
                    }
                }),
                (insert ChatHistory {
                    summary := 'Exploring reinforcement learning concepts',
                    messages := {
                        (insert Message {
                            role := 'user',
                            body := 'Can you explain what policy gradient methods are in RL?',
                            timestamp := <datetime>'2024-01-08T14:30:00Z',
                            sources := {'Sutton-Barto-RL-Book-Ch13', 'arxiv:1904.12901'}
                        }),
                        (insert Message {
                            role := 'assistant',
                            body := 'Policy gradient methods are a class of reinforcement learning algorithms that directly optimize the policy...',
                            timestamp := <datetime>'2024-01-08T14:30:10Z',
                            sources := {'Sutton-Barto-RL-Book-Ch13', 'spinning-up.openai.com'}
                        })
                    }
                })
            }
        };


        # Insert chat histories for Bob
        update User
        filter .name = 'bob'
        set {
            chats := {
                (insert ChatHistory {
                    summary := 'Discussion about database sharding strategies',
                    messages := {
                        (insert Message {
                            role := 'user',
                            body := 'What are the pros and cons of different sharding strategies?',
                            timestamp := <datetime>'2024-01-05T16:15:00Z',
                            sources := {'martin-kleppmann-ddia-ch6', 'aws.amazon.com/sharding-patterns'}
                        }),
                        (insert Message {
                            role := 'assistant',
                            body := 'The main sharding strategies include range-based, hash-based, and directory-based sharding...',
                            timestamp := <datetime>'2024-01-05T16:15:08Z',
                            sources := {'martin-kleppmann-ddia-ch6', 'mongodb.com/docs/sharding'}
                        }),
                        (insert Message {
                            role := 'user',
                            body := 'Could you elaborate on hash-based sharding?',
                            timestamp := <datetime>'2024-01-05T16:16:00Z',
                            sources := {'mongodb.com/docs/sharding'}
                        })
                    }
                })
            }
        };\
        """,
    )
